# Generated by Django 5.1.6 on 2025-02-16 01:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caja', models.PositiveIntegerField(verbose_name='Caja')),
                ('carpeta', models.PositiveIntegerField(blank=True, null=True, verbose_name='Carpeta')),
                ('serie', models.CharField(default='Serie Default', max_length=255)),
                ('subs', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo', models.CharField(default='Título Default', max_length=255)),
                ('finicial', models.DateField(default=datetime.date.today)),
                ('ffinal', models.DateField(default=datetime.date.today)),
                ('folios', models.PositiveIntegerField(default=1)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
