# Generated by Django 5.1.6 on 2025-02-16 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0003_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serie_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subserie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subseries', to='aplicacion1.serie')),
            ],
        ),
    ]
