# Generated by Django 5.1.6 on 2025-02-16 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0004_subs_subserie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subs',
            name='serie_nombre',
        ),
        migrations.AddField(
            model_name='subs',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='aplicacion1.serie'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Subserie',
        ),
    ]
