# Generated by Django 5.1.6 on 2025-02-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0005_remove_subs_serie_nombre_subs_serie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subs',
            old_name='nombre',
            new_name='Subs',
        ),
        migrations.RemoveField(
            model_name='subs',
            name='serie',
        ),
        migrations.AddField(
            model_name='subs',
            name='serie_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
