# Generated by Django 5.1.6 on 2025-02-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0006_rename_nombre_subs_subs_remove_subs_serie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subs',
            old_name='Subs',
            new_name='nombre',
        ),
    ]
