# Generated by Django 5.1.6 on 2025-02-18 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0007_rename_subs_subs_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subs',
            old_name='nombre',
            new_name='Subs',
        ),
    ]
